[General]
BackgroundImage="Backgrounds/backgroundArch.jpeg"

[Design]
PrimaryColor=#ffffff
SecondaryColor=#cccccc
AccentColor=#0078d4
BackgroundColor=#1a1a1a
FontFamily=Noto Sans
ClockFontSize=72
DateFontSize=22